services:
  rabbit:
    image: rabbitmq:3.8.10-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 1883:1883
      - 15672:15672
    volumes:
      - ./config/rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins
  raspisensor:
    build: .
    volumes:
      - /sys/bus/w1/devices:/sys/bus/w1/devices
